### PR TITLE
Rework Recyclerview for multiple view Types

### PR DESCRIPTION
**Pull request by jstsddg**
Started implementation for #21

### CODE REVIEW

**Comment by jstsddg** [comment]
My first idear was to create a RecyclerView with different types, but I switched to two different RecyclerViews

- The first RecyclerView holds all days of one week
- The second RecyclerView holds all Vorlesungen of one day

**Comment by jstsddg** [comment]
@felixwortmann @patrickstecker
I need some help with styling the elements.
The functionality was already completely moved to the new design, but some styling adjustments still need to be done.

**Review by patrickstecker — APPROVED** [review]
Looks great, LGTM

**Comment by patrickstecker** [comment]
Pls resolve conflicts:D

**Pull request merged**
